version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: back-end
      dockerfile: ./Dockerfile
    ports:
      - 6060:6060

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: UI
      dockerfile: ./Dockerfile
    ports:
      - 8040:8040

volumes:
  mongo_volume: